# This script provides Travis-CI with all the necessary information for building
# pynusmv on various platforms.
#
# -- Note: --
# On linux, this script assumes the presence of the following tools: 
# - SYTEM : zip, build-essential, flex, bison, zlib1g-dev, libexpat-dev, wget
# - PYTHON: python3, python3-dev, python3-pip, setuptools
# 
# This file is part of the pynusmv distribution. As such it is licensed to you
# under the term of the LGPLv2. For more information regarding the legal aspect
# of this licensing, please refer to the full text of the license on the free
# software foundation website.
#
# Author: X. Gillard <xavier.gillard [at] uclouvain.be>
# Modified by: D. Bresolin <davide.bresolin [at] unipd.it>
#

os:
  - linux
  - osx
  
language: python

python: 
  - 3.10

matrix:
  exclude:
    - python: 3.10
  include:
    - os: linux
      python: 3.10
    - os: osx
      language: generic
  
before_install:
  # -- LINUX --
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y swig                                                ; fi
  # PATCHELF : Download then build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xpf patchelf-0.9.tar.gz                                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd patchelf-0.9 && ./configure && make && sudo make install && cd ..        ; fi
  # -- OSX   --
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install flex           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install bison          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install swig           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install python@3.10    ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install coveralls ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coverage run --source=pynusmv setup.py test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then python3 setup.py test                       ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls                                   ; fi
