[tool.cibuildwheel]
# Only build on CPython 3.9, 3.10 and 3.11
build = ["cp39-*", "cp310-*", "cp311-*"]

# Skip muslinux builds
skip = "*musllinux*"

[tool.cibuildwheel.macos]
# Build intel and universal 2 binaries
archs = "x86_64 universal2"

[tool.cibuildwheel.linux]
# Install system library
before-all = "yum install -y flex"
# Build only x86_64 architecture
archs = ["x86_64"]

