name: Build Wheels

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0rc3
        env:
            CIBW_ARCHS_MACOS: x86_64 arm64
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
        #   package-dir: .
        #   output-dir: wheelhouse
            config-file: "{package}/pyproject.toml"

      - name: Release wheels
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl
